# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  push:
    branches: [ main ]
jobs:
  github-actions-environment-variables-ubuntu:
    runs-on: ubuntu-latest
    steps:
     - name: Run with env var
       run: server.js
       env: 
        MONGO_DB: ${{ secrets.MONGO_DB }} 

  github-actions-environment-variables-windows:
    runs-on: windows-latest
    steps:
     - name: Run with env var
       run: server.js
       env: 
        MONGO_DB: ${{ secrets.MONGO_DB }} 

  github-actions-environment-variables-macos:
    runs-on: macos-latest
    steps:
     - name: Run with env var
       run: server.js
       env: 
        MONGO_DB: ${{ secrets.MONGO_DB }} 
      
